headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\Proyectos Freelance\\bonocopas-wheel\\frontend\\.netlify\\functions-internal"
functionsDirectoryOrigin = "config"

[dev]
command = "npm run dev"

[functions]

[functions."*"]

[build]
publish = "C:\\Proyectos Freelance\\bonocopas-wheel\\frontend\\.output\\public"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Proyectos Freelance\\bonocopas-wheel\\frontend\\.netlify\\functions-internal"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_nuxt/*"

[headers.values]
Content-Type = "application/javascript"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]